name: SYNTHETIC-TEST-cpuhog_forkjoin_00000008

on:
  workflow_dispatch:
    inputs:
      OVERWRITTEN:
        description: 'overwritten fields'
        required: true
      PAYLOAD_URL:
        description: 'url to payload'
        required: true
jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: ghcr.io/faasr/github-actions-r:dev
    env:
      TOKEN: ${{ secrets.My_GitHub_Account_PAT }}
      My_GitHub_Account_PAT: ${{ secrets.My_GitHub_Account_PAT }}
      My_Minio_Bucket_ACCESS_KEY: ${{ secrets.My_Minio_Bucket_ACCESS_KEY }}
      My_Minio_Bucket_SECRET_KEY: ${{ secrets.My_Minio_Bucket_SECRET_KEY }}
      OVERWRITTEN: ${{ github.event.inputs.OVERWRITTEN }}
      PAYLOAD_URL: ${{ github.event.inputs.PAYLOAD_URL }}
    steps:
    - name: run Python
      run: |
        cd /action
        python3 faasr_entry.py
